name: digit_recognizer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=22.1.0
  - autopep8=1.6.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cachecontrol=0.12.11
  - cairo=1.16.0
  - cffi=1.15.1
  - colorama=0.4.6
  - commonmark=0.9.1
  - contextlib2=21.6.0
  - cryptography=39.0.1
  - cython=0.29.32
  - decorator=5.1.1
  - distlib=0.3.6
  - dnspython=2.2.1
  - docopt=0.6.2
  - flit-core=3.8.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.69.1
  - html5lib=1.1
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libcurl=7.82.0
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=14.0.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - ncurses=6.2
  - numpy-base=1.24.3
  - openssl=1.1.1u
  - ordered-set=4.1.0
  - pcre=8.45
  - pefile=2022.5.30
  - pip=21.3.1
  - pixman=0.40.0
  - ply=3.11
  - prettytable=3.5.0
  - pybind11=2.10.1
  - pybind11-global=2.10.1
  - pycairo=1.21.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pycurl=7.45.1
  - pydantic=1.10.2
  - pyopenssl=23.0.0
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.0
  - python_abi=3.9
  - pyyaml=6.0
  - readline=8.1
  - reportlab=3.6.12
  - resolvelib=0.8.1
  - retrying=1.3.3
  - setuptools=59.2.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tomli=2.0.1
  - typing_extensions=4.4.0
  - tzdata=2021e
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - absl-py==1.0.0
      - astunparse==1.6.3
      - cachetools==4.2.4
      - certifi==2021.10.8
      - charset-normalizer==2.0.8
      - clang==5.0
      - cycler==0.11.0
      - easyprocess==0.3
      - entrypoint2==0.2.4
      - flatbuffers==1.12
      - fonttools==4.28.3
      - gast==0.4.0
      - google-auth==2.3.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.42.0
      - h5py==3.6.0
      - idna==3.3
      - importlib-metadata==4.8.2
      - jeepney==0.7.1
      - joblib==1.1.0
      - keras==2.7.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.2
      - libclang==12.0.0
      - markdown==3.3.6
      - matplotlib==3.5.1
      - mss==6.1.0
      - numpy==1.21.4
      - oauthlib==3.1.1
      - opencv-python==4.8.0.74
      - opt-einsum==3.3.0
      - packaging==21.3
      - pandas==1.3.5
      - pillow==10.0.0
      - protobuf==3.19.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.1.0
      - pyparsing==3.0.6
      - pyscreenshot==3.1
      - python-dateutil==2.8.2
      - pytz==2021.3
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - rsa==4.8
      - scikit-learn==1.0.1
      - scipy==1.7.3
      - seaborn==0.11.2
      - tensorboard==2.7.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - tensorflow==2.7.0
      - tensorflow-estimator==2.7.0
      - tensorflow-io-gcs-filesystem==0.22.0
      - termcolor==1.1.0
      - threadpoolctl==3.0.0
      - typing-extensions==4.7.1
      - urllib3==1.26.7
      - werkzeug==2.0.2
      - wrapt==1.13.3
      - zipp==3.6.0
